name: sliver_expansion
description: Sliver expansion primitives for Flutter (SliverExpansible + SliverExpansionTile).
version: 0.1.0

homepage: https://github.com/vanvixi/sliver_expansible
repository: https://github.com/vanvixi/sliver_expansible
issue_tracker: https://github.com/vanvixi/sliver_expansible/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - sliver
  - expansion
  - flutter
  - ui

screenshots:
  - description: Sliver expansion demo
    path: screenshots/demo.gif
